export const ERRORS = {
  USER_NOT_FOUND: 'User not found',
  OLD_PASSWORD_INCORRECT: 'Old password incorrect',
  USER_CREATED_ERROR: 'User created error',
  ERROR: 'Error',
  TRACK_NOT_FOUND: 'Track not found',
  TRACK_NOT_FOUND_IN_FAVORITES: 'Track not found in favorites tracks list',
  TRACK_CREATED_ERROR: 'Track created error',
  ARTIST_NOT_FOUND: 'Artist not found',
  ARTIST_NOT_FOUND_IN_FAVORITES: 'Artist not found in favorites artists list',
  ARTIST_CREATED_ERROR: 'Artist created error',
  ALBUM_NOT_FOUND: 'Album not found',
  ALBUM_NOT_FOUND_IN_FAVORITES: 'Album not found in favorites albums list',
  ALBUM_CREATED_ERROR: 'Album created error',
};
